version: '3.8'
services:
  ns3:
    build: .
    volumes:
      - ./src:/usr/workspace/ns-allinone-3.41/ns-3.41/user_src
      - ./libs:/usr/workspace/ns-allinone-3.41/ns-3.41/libs
      - ./traces:/usr/workspace/ns-allinone-3.41/ns-3.41/traces
      - ./run_ns3.sh:/usr/workspace/ns-allinone-3.41/ns-3.41/run_ns3.sh # Mounting run_ns3.sh
    ulimits:
      nofile:
        soft: 1024000
        hard: 1024000
