name: Check if Compiles

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-if-compiles:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Docker Compose
      run: docker-compose run ns3
